<%@include file="../includes/check_auth_layer3.jsp"%>
<%
    
    int i = 0;
    
%>
    
<div class="freetext">
    Hi <% out.println(v_firstName+" "+v_lastName+" ("+v_userName+")"); %>, Welcome to <%=v_appName%>.<br/>
    This web report repository is used to view Published Static Report for business and Operation team. <br/>
    This Report is automatically generated by Muamalat Data Warehouse (MDW) System. <br/>
    <br/>
    <br/>
    Any request or changes needed regarding layout, content and file extension on published report must be coordinated with Report Owner.  
    <br/>
    <br/>
    <br/>
</div>

  
<b>Notification :</b>  
<div>
    
    <table class="tableinfonotif" width="700px">
        <thead>
            <tr>
      
                <th width="100px">To Group</th>
                <th width="200px">To Level</th>
                <th>Created By</th>
                <th>Created Time</th>
                <th>Message</th>
                
            </tr>
        </thead>

        <tbody>

            <%
                 

            
                
                try {
                    ResultSet resultSet = null;
                    Database db = new Database();
                    try {
                        db.connect(1);
                        String sql;

                        sql = "select a.id,case when b.group_name is null then 'All' else b.group_name end group_name,"
                              + "case when c.level_name is null then 'All' else c.level_name end level_name,a.message,a.status,a.inorder, "
                              + "d.first_name||' '||d.last_name fullname,to_char(a.created_time,'YYYY-MM-DD HH24:MI:SS') created_time  "
                              + " from t_notification a left join t_user_group b on a.group_id=b.id "
                              + "left join t_user_level c on a.level_id=c.id left join t_user d on a.userid=d.id "
                              + "where (a.group_id="+v_userGroup+" and a.level_id="+v_userLevel+") "
                                + "OR (a.group_id=0 and a.level_id="+v_userLevel+") "
                                + "OR  (a.group_id="+v_userGroup+" and a.level_id=0)"
                                + "OR  (a.group_id=0 and a.level_id=0) and a.status=1 ";    

                        
                        sql += " order by created_time desc,inorder asc";
                        
                       //debug mode            
                        if (v_debugMode.equals("1")) {
                        out.println("<div class=sql>" + sql + "</div>");
                        }

                        resultSet = db.executeQuery(sql);
                        String rowstate = "even";
                        
                        while (resultSet.next()) {
                            i++;

                            if (i % 2 == 0) {
                                rowstate = "even";
                            } else {
                                rowstate = "odd";
                            }


                            out.println("<tr id=rows_"+resultSet.getString("ID")+" class=" + rowstate + "> ");
   
                        
                             out.println("<td> " + resultSet.getString("group_name") + " </td>");
                             out.println("<td> " + resultSet.getString("level_name") + " </td>");
                             out.println("<td> " + resultSet.getString("fullname") + " </td>");
                             out.println("<td> " + resultSet.getString("created_time") + " </td>");
                             out.println("<td> " + resultSet.getString("message") + " </td>");
                            
                            out.println("</tr> ");
                        }

                    } catch (SQLException Sqlex) {
                        out.println("<div class=sql>" + Sqlex.getMessage() + "</div>");
                    } finally {
                        db.close();
                            if (resultSet != null) resultSet.close(); 
                    }
                } catch (Exception except) {
                    out.println("<div class=sql>" + except.getMessage() + "</div>");
                }

            %>
        </tbody>
        <tfoot>
            <tr>
                <td>Total</td>
                <td> <%=i%> Record(s)</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
            </tr>
        </tfoot>
    </table>
 </div> 

<b>User Info :</b>
<div >
    
    <table class="tableinfonotif" width="700px">
        <thead>
            <tr>
      
                <th width="100px">Info</th>
                <th width="200px">Description</th>
                
            </tr>
        </thead>

        <tbody>

            <%
                 

            
                
                try {
                    ResultSet resultSet = null;
                    Database db = new Database();
                    try {
                        db.connect(1);
                        String sql;

                        sql = " select 'Username' Info, username description "
                              +" from v_user_info "
                              +" where id="+v_userID+" "
                              +" union all  "
                                +" select 'Name' Info, fullname description "
                              +" from v_user_info "
                              +" where id="+v_userID+" "
                                 +" union all  "
                              +" select 'Employee ID' Info, emp_id description "
                              +" from v_user_info "
                              +" where id="+v_userID+" "
                              +" union all  "
                              +" select 'Title' Info, title description "
                              +" from v_user_info "
                              +" where id="+v_userID+" "
                                +" union all  "
                              +" select 'Level' Info, level_name description "
                              +" from v_user_info "
                              +" where id="+v_userID+" "
                              +" union all  "
                              +" select 'Group' Info, group_name description "
                              +" from v_user_info "
                              +" where id="+v_userID+" "
                              +" union all  "
                              +" select 'Email' Info, email description "
                              +" from v_user_info "
                              +" where id="+v_userID+" "
                              +" union all  "
                              +" select 'Extension' Info, contact_ext description "
                              +" from v_user_info "
                              +" where id="+v_userID+" "
                              +" union all  "
                              +" select 'ip address' Info, ip_address description "
                              +" from v_user_info "
                              +" where id="+v_userID+" "
                              +" union all  "
                              +" select 'status login' Info, status_login description "
                              +" from v_user_info "
                              +" where id="+v_userID+" "
                              +" union all  "
                              +" select 'Last login' Info, last_login description "
                              +" from v_user_info "
                              +" where id="+v_userID+" "
                              +" union all  "
                              +" select 'Created By' Info, creator_name description "
                              +" from v_user_info "
                              +" where id="+v_userID+" "
//                              +" union all  "
//                              +" select 'Jumlah Report Akses' Info, jml_report description "
//                              +" from v_user_info "
//                              +" where id="+v_userID+" "
                              +" union all  "
                              +" select 'User Today Login' Info, jml_login description "
                              +" from (select count(1)::text jml_login from v_user_today_login  ) a "
                              +"  ";
                           
                        
                        
                       //debug mode            
                        if (v_debugMode.equals("1")) {
                        out.println("<div class=sql>" + sql + "</div>");
                        }

                        resultSet = db.executeQuery(sql);
                        String rowstate = "even";
                        
                        while (resultSet.next()) {
                            i++;

                            if (i % 2 == 0) {
                                rowstate = "even";
                            } else {
                                rowstate = "odd";
                            }


                            out.println("<tr id=rows_"+v_userID+" class=" + rowstate + "> ");
   
                        
                             out.println("<td> " + resultSet.getString("Info") + " </td>");
                             out.println("<td> " + resultSet.getString("description") + " </td>");
                           
                            out.println("</tr> ");
                        }

                    } catch (SQLException Sqlex) {
                        out.println("<div class=sql>" + Sqlex.getMessage() + "</div>");
                    } finally {
                        db.close();
                            if (resultSet != null) resultSet.close(); 
                    }
                } catch (Exception except) {
                    out.println("<div class=sql>" + except.getMessage() + "</div>");
                }

            %>
        </tbody>
        <tfoot>
            <tr>
                <td></td>
                <td> </td>
                
            </tr>
        </tfoot>
    </table>
                
</div>

        
        